# Generated by Django 5.0.3 on 2024-06-12 14:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_mas', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_mas', models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato'), ('Ave', 'Ave'), ('Reptil', 'Reptil'), ('Roedores', 'Roedores'), ('Conejo', 'Conejo')], max_length=45)),
                ('raza', models.CharField(max_length=45)),
                ('nom_mas', models.CharField(max_length=45)),
                ('fecha_nac', models.DateField()),
                ('foto', models.ImageField(upload_to='mascotas/')),
            ],
            options={
                'db_table': 'mascota',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MascotaServicio',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_servicio', models.DateField()),
            ],
            options={
                'db_table': 'mascota_servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_pro', models.AutoField(primary_key=True, serialize=False)),
                ('nom_pro', models.CharField(max_length=45)),
                ('desc_pro', models.CharField(max_length=60)),
                ('precio_pro', models.DecimalField(decimal_places=3, max_digits=10)),
                ('foto_pro', models.ImageField(upload_to='producto/')),
                ('stock_pro', models.FloatField()),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductoUsuario',
            fields=[
                ('codpu', models.AutoField(db_column='codPU', primary_key=True, serialize=False)),
                ('cant', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
            options={
                'db_table': 'producto_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_serv', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=70)),
                ('precio', models.FloatField()),
                ('imagen', models.ImageField(upload_to='servicio/')),
            ],
            options={
                'db_table': 'servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_persona', models.IntegerField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(blank=True, max_length=45, null=True, unique=True)),
                ('pass_field', models.CharField(blank=True, db_column='pass', max_length=45, null=True)),
                ('nom', models.CharField(blank=True, max_length=45, null=True)),
                ('ape', models.CharField(blank=True, max_length=45, null=True)),
                ('dir', models.CharField(blank=True, max_length=45, null=True)),
                ('tel', models.CharField(blank=True, max_length=45, null=True)),
                ('correo', models.CharField(blank=True, max_length=45, null=True)),
                ('tipo', models.IntegerField(blank=True, choices=[(0, 'Administrador'), (1, 'Cliente')], null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='BlogImg', verbose_name='imagen')),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nombre')),
                ('FCreacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
            ],
            options={
                'verbose_name': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fech publicacion')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='BlogImg', verbose_name='Imagen')),
                ('Fcreacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creacion')),
                ('Fedicion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de edicion')),
                ('categorias', models.ManyToManyField(to='bd_mascota.categoria', verbose_name='Categorias')),
                ('id_persona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bd_mascota.usuario')),
            ],
            options={
                'verbose_name': 'Post',
            },
        ),
    ]
